import { HistoryMessage, Memory, StoryCard } from "./stories";

/**
 * A Delta describes a single reversible mutation to session
 * state. Every delta carries both the previous value and the
 * next value so it can be applied (redo) or reversed (undo)
 * without additional lookups.
 */
export type Delta =
  | {
      type: "message:add";
      message: HistoryMessage;
    }
  | {
      type: "message:edit";
      messageId: string;
      prev: string;
      next: string;
    }
  | {
      type: "message:remove";
      message: HistoryMessage;
    }
  | {
      type: "memory:add";
      memory: Memory;
    }
  | {
      type: "memory:edit";
      memoryId: string;
      prev: string;
      next: string;
    }
  | {
      type: "memory:remove";
      memory: Memory;
    }
  | {
      type: "storyCard:add";
      card: StoryCard;
    }
  | {
      type: "storyCard:edit";
      cardId: string;
      prev: Partial<StoryCard>;
      next: Partial<StoryCard>;
    }
  | {
      type: "storyCard:remove";
      card: StoryCard;
    };

/**
 * A DeltaTransaction groups one or more deltas that should be
 * undone and redone as a single atomic step.
 *
 * Example: clicking "Send" generates a transaction that may
 * contain — in order:
 *   1. message:add  (the user input message)
 *   2. message:add  (the AI response)
 *   3. storyCard:add (a card injected by an onOutput hook)
 *   4. memory:add   (a memory auto-generated by the engine)
 *
 * Pressing Ctrl+Z undoes all four at once.
 */
export interface DeltaTransaction {
  id: string;
  /** Human-readable label shown in the undo history. */
  description: string;
  deltas: Delta[];
  timestamp: number;
}

/**
 * The full in-memory state of an active adventure session.
 * Persisted to IndexedDB incrementally (transactions appended,
 * not full rewrites).
 *
 * The session is the source of truth for the game store.
 * The UI reads from the store; the engine writes to it via
 * delta transactions.
 */
export interface Session {
  /** Matches the parent Story.id. */
  storyId: string;
  /**
   * The ordered list of HistoryMessage IDs from the root to
   * the current leaf node.
   */
  activePath: string[]
  /**
   * Stack of committed transactions. The most recent is last.
   * Undo pops from this and pushes to redoStack.
   */
  undoStack: DeltaTransaction[];
  /**
   * Stack of undone transactions. Cleared whenever a new
   * transaction is committed (standard undo-tree behaviour).
   */
  redoStack: DeltaTransaction[];
  /** True while the engine is mid-turn (generating or running hooks). */
  isGenerating: boolean;
  /**
   * ID of the transaction currently being assembled by the engine.
   * The engine opens a transaction on send, accumulates deltas,
   * then commits it when onOutput finishes.
   */
  pendingTransactionId: string | null;
}